services:
  fastapi:
    build: .
    container_name: fastapi_app_evaluaciones
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=${MONGO_URI}
      - PYTHONPATH=/app/src
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
