version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app_litstorm
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - PYTHONPATH=/app/src  # Clave para resolver imports
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend_network
    volumes:
      - .:/app  # Montar el código como volumen para desarrollo
    command: >
      sh -c "uvicorn src.app:app
      --host 0.0.0.0
      --port 8000
      --reload"  # Solo para desarrollo

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256  # Autenticación más segura
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_network
    security_opt:
      - no-new-privileges:true
    ports:
      - "5432:5432"  # Opcional: exponer puerto para herramientas externas

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge